"""add cascade delete to user subscriptions

Revision ID: 1723b96b2d76
Revises: fa2fa8ad97fa
Create Date: 2025-03-03 16:50:45.524045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1723b96b2d76'
down_revision = 'fa2fa8ad97fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 